import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes, scryptSync } from "node:crypto";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env.local");
const args = parseArgs(process.argv.slice(2));
const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};

const adminEmail = args.email || existing.ADMIN_EMAIL || "admin@example.com";
const adminPassword = args.password || randomPassword();
const sessionSecret = existing.ADMIN_SESSION_SECRET || randomBytes(48).toString("base64url");
const passwordHash = hashPassword(adminPassword);

const nextEnv = {
  NEXT_PUBLIC_SITE_URL: existing.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: existing.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || "pk_test_replace_me",
  STRIPE_SECRET_KEY: existing.STRIPE_SECRET_KEY || "sk_test_replace_me",
  STRIPE_WEBHOOK_SECRET: existing.STRIPE_WEBHOOK_SECRET || "whsec_replace_me",
  ADMIN_EMAIL: adminEmail,
  ADMIN_PASSWORD_HASH: passwordHash,
  ADMIN_SESSION_SECRET: sessionSecret,
  ...preserveUnknown(existing)
};

writeFileSync(envPath, serializeEnv(nextEnv), "utf8");

console.log("Auth setup concluído.");
console.log(`Ficheiro: ${envPath}`);
console.log(`ADMIN_EMAIL=${adminEmail}`);
console.log(`ADMIN_PASSWORD=${adminPassword}`);
console.log("Guarda esta password agora. Ela não volta a ser mostrada.");

function hashPassword(password) {
  const salt = randomBytes(16).toString("hex");
  const hash = scryptSync(password, salt, 64).toString("hex");
  return `scrypt:${salt}:${hash}`;
}

function randomPassword() {
  return randomBytes(18).toString("base64url");
}

function parseArgs(values) {
  const result = {};
  for (let index = 0; index < values.length; index += 1) {
    if (values[index] === "--email") {
      result.email = values[index + 1];
      index += 1;
    } else if (values[index] === "--password") {
      result.password = values[index + 1];
      index += 1;
    }
  }
  return result;
}

function parseEnv(contents) {
  return contents.split(/\r?\n/).reduce((acc, line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) {
      return acc;
    }
    const [key, ...rest] = trimmed.split("=");
    acc[key] = rest.join("=");
    return acc;
  }, {});
}

function preserveUnknown(env) {
  const known = new Set([
    "NEXT_PUBLIC_SITE_URL",
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET",
    "ADMIN_EMAIL",
    "ADMIN_PASSWORD_HASH",
    "ADMIN_SESSION_SECRET"
  ]);
  return Object.fromEntries(Object.entries(env).filter(([key]) => !known.has(key)));
}

function serializeEnv(env) {
  const lines = [
    "# Generated by npm run setup",
    ...Object.entries(env).map(([key, value]) => `${key}=${value}`)
  ];
  return `${lines.join("\n")}\n`;
}
